services:
  # Main php runner
  php:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: laravel_php
    ports:
      - "80:80"
    volumes:
      - ./:/app
    # environment:
    #     - WEB_DOCUMENT_ROOT=/app/public
